// Mocks generated by Mockito 5.4.6 from annotations
// in caderno_digital_app/test/core/services/ai_assistant_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:caderno_digital_app/core/network/api_service.dart' as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> saveToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#saveToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveUserData(Map<String, dynamic>? userMap) =>
      (super.noSuchMethod(
            Invocation.method(#saveUserData, [userMap]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>?> getUserData() =>
      (super.noSuchMethod(
            Invocation.method(#getUserData, []),
            returnValue: _i4.Future<Map<String, dynamic>?>.value(),
          )
          as _i4.Future<Map<String, dynamic>?>);

  @override
  _i4.Future<_i2.Response> post(
    String? endpoint,
    Map<String, dynamic>? body, {
    bool? requireAuth = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endpoint, body],
              {#requireAuth: requireAuth},
            ),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #post,
                  [endpoint, body],
                  {#requireAuth: requireAuth},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> get(String? endpoint, {bool? requireAuth = true}) =>
      (super.noSuchMethod(
            Invocation.method(#get, [endpoint], {#requireAuth: requireAuth}),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #get,
                  [endpoint],
                  {#requireAuth: requireAuth},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> fetchUrl(String? url, {bool? requireAuth = true}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUrl, [url], {#requireAuth: requireAuth}),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #fetchUrl,
                  [url],
                  {#requireAuth: requireAuth},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> put(
    String? endpoint,
    Map<String, dynamic>? body, {
    bool? requireAuth = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endpoint, body],
              {#requireAuth: requireAuth},
            ),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #put,
                  [endpoint, body],
                  {#requireAuth: requireAuth},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> delete(
    String? endpoint, {
    bool? requireAuth = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [endpoint], {#requireAuth: requireAuth}),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #delete,
                  [endpoint],
                  {#requireAuth: requireAuth},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> deleteWithBody(
    String? endpoint,
    Map<String, dynamic>? body, {
    bool? requireAuth = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteWithBody,
              [endpoint, body],
              {#requireAuth: requireAuth},
            ),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(
                  #deleteWithBody,
                  [endpoint, body],
                  {#requireAuth: requireAuth},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Response> forgotPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#forgotPassword, [email]),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#forgotPassword, [email]),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> resetPassword({
    required String? email,
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #email: email,
              #code: code,
              #newPassword: newPassword,
            }),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#resetPassword, [], {
                  #email: email,
                  #code: code,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);

  @override
  _i4.Future<_i2.Response> updateProfile({
    required String? name,
    dynamic imageFile,
    String? bio,
    String? institution,
    String? preferredColor,
    String? specialties,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #name: name,
              #imageFile: imageFile,
              #bio: bio,
              #institution: institution,
              #preferredColor: preferredColor,
              #specialties: specialties,
            }),
            returnValue: _i4.Future<_i2.Response>.value(
              _FakeResponse_0(
                this,
                Invocation.method(#updateProfile, [], {
                  #name: name,
                  #imageFile: imageFile,
                  #bio: bio,
                  #institution: institution,
                  #preferredColor: preferredColor,
                  #specialties: specialties,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Response>);
}
