// Mocks generated by Mockito 5.4.6 from annotations
// in caderno_digital_app/test/features/canvas/controllers/canvas_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i9;
import 'dart:ui' as _i11;

import 'package:caderno_digital_app/core/network/realtime_service.dart' as _i10;
import 'package:caderno_digital_app/features/canvas/models/image_block_model.dart'
    as _i8;
import 'package:caderno_digital_app/features/canvas/models/local_page_model.dart'
    as _i5;
import 'package:caderno_digital_app/features/canvas/models/stroke_model.dart'
    as _i6;
import 'package:caderno_digital_app/features/canvas/models/text_block_model.dart'
    as _i7;
import 'package:caderno_digital_app/features/canvas/repositories/canvas_repository.dart'
    as _i3;
import 'package:flutter/foundation.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [CanvasRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCanvasRepository extends _i1.Mock implements _i3.CanvasRepository {
  MockCanvasRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.LocalPage>> getPagesByNotebook(
    int? notebookId,
    int? notebookServerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPagesByNotebook, [
              notebookId,
              notebookServerId,
            ]),
            returnValue: _i4.Future<List<_i5.LocalPage>>.value(
              <_i5.LocalPage>[],
            ),
          )
          as _i4.Future<List<_i5.LocalPage>>);

  @override
  _i4.Stream<List<_i5.LocalPage>> watchPagesByNotebook(int? notebookId) =>
      (super.noSuchMethod(
            Invocation.method(#watchPagesByNotebook, [notebookId]),
            returnValue: _i4.Stream<List<_i5.LocalPage>>.empty(),
          )
          as _i4.Stream<List<_i5.LocalPage>>);

  @override
  _i4.Future<void> savePage(_i5.LocalPage? page, int? notebookServerId) =>
      (super.noSuchMethod(
            Invocation.method(#savePage, [page, notebookServerId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i5.LocalPage?> createNewPage(
    int? notebookId,
    int? pageNumber,
    bool? isLandscape,
    int? notebookServerId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createNewPage, [
              notebookId,
              pageNumber,
              isLandscape,
              notebookServerId,
            ]),
            returnValue: _i4.Future<_i5.LocalPage?>.value(),
          )
          as _i4.Future<_i5.LocalPage?>);

  @override
  _i4.Future<void> saveSingleStroke(int? pageId, _i6.Stroke? stroke) =>
      (super.noSuchMethod(
            Invocation.method(#saveSingleStroke, [pageId, stroke]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveSingleTextBlock(int? pageId, _i7.TextBlock? block) =>
      (super.noSuchMethod(
            Invocation.method(#saveSingleTextBlock, [pageId, block]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteSingleStroke(int? pageId, String? clientStrokeId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteSingleStroke, [pageId, clientStrokeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveSingleImageBlock(int? pageId, _i8.ImageBlock? img) =>
      (super.noSuchMethod(
            Invocation.method(#saveSingleImageBlock, [pageId, img]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePageMetadata(
    int? pageId,
    String? title,
    String? footer, {
    String? extractedText,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updatePageMetadata,
              [pageId, title, footer],
              {#extractedText: extractedText},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deletePage(int? pageId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePage, [pageId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateNotebookMetadata(
    int? notebookId,
    String? lineType,
    double? lineSpacing,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateNotebookMetadata, [
              notebookId,
              lineType,
              lineSpacing,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> triggerSyncRadar(int? pageId) =>
      (super.noSuchMethod(
            Invocation.method(#triggerSyncRadar, [pageId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> savePageToCloud(
    _i5.LocalPage? page,
    int? notebookServerId,
    String? myUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#savePageToCloud, [
              page,
              notebookServerId,
              myUserId,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> uploadAudio(
    int? notebookServerId,
    String? filename,
    _i9.Uint8List? bytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadAudio, [
              notebookServerId,
              filename,
              bytes,
            ]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<String?> uploadImage(
    int? notebookServerId,
    String? filename,
    _i9.Uint8List? bytes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [
              notebookServerId,
              filename,
              bytes,
            ]),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);
}

/// A class which mocks [RealtimeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockRealtimeService extends _i1.Mock implements _i10.RealtimeService {
  MockRealtimeService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ValueNotifier<_i10.RealtimeStatus> get statusNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#statusNotifier),
            returnValue: _FakeValueNotifier_0<_i10.RealtimeStatus>(
              this,
              Invocation.getter(#statusNotifier),
            ),
          )
          as _i2.ValueNotifier<_i10.RealtimeStatus>);

  @override
  _i4.Stream<Map<String, dynamic>> get onStrokeReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onStrokeReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onTextReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onTextReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onImageReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onImageReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onViewportReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onViewportReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onFollowUpdateReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onFollowUpdateReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<List<dynamic>> get onUsersUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#onUsersUpdated),
            returnValue: _i4.Stream<List<dynamic>>.empty(),
          )
          as _i4.Stream<List<dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onPageEventReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onPageEventReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onPageUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#onPageUpdated),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onHandEventReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onHandEventReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onRemoteUploading =>
      (super.noSuchMethod(
            Invocation.getter(#onRemoteUploading),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onLiveInviteReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onLiveInviteReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onVoiceCallStarted =>
      (super.noSuchMethod(
            Invocation.getter(#onVoiceCallStarted),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onVoiceStateReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onVoiceStateReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onUserActivityReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onUserActivityReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onPointerMoveReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onPointerMoveReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onChatMessageReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onChatMessageReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onAudioMessageReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onAudioMessageReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onChatSyncRequestReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onChatSyncRequestReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onChatSyncResponseReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onChatSyncResponseReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onReactionReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onReactionReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onCollectiveSyncRequested =>
      (super.noSuchMethod(
            Invocation.getter(#onCollectiveSyncRequested),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onFullStateRequested =>
      (super.noSuchMethod(
            Invocation.getter(#onFullStateRequested),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onFullStateReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onFullStateReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onPageFingerprintReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onPageFingerprintReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onCloudSyncSignalReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onCloudSyncSignalReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Stream<Map<String, dynamic>> get onGlobalActionReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onGlobalActionReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  _i4.Stream<Map<String, dynamic>> get onWebRTCSignalReceived =>
      (super.noSuchMethod(
            Invocation.getter(#onWebRTCSignalReceived),
            returnValue: _i4.Stream<Map<String, dynamic>>.empty(),
          )
          as _i4.Stream<Map<String, dynamic>>);

  @override
  _i4.Future<void> initConnection() =>
      (super.noSuchMethod(
            Invocation.method(#initConnection, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> joinNotebookChannel({required int? notebookId}) =>
      (super.noSuchMethod(
            Invocation.method(#joinNotebookChannel, [], {
              #notebookId: notebookId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void sendWebRTCSignal(int? notebookId, Map<String, dynamic>? signalData) =>
      super.noSuchMethod(
        Invocation.method(#sendWebRTCSignal, [notebookId, signalData]),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<bool> broadcastStroke({
    required int? notebookId,
    required Map<String, dynamic>? strokeData,
    String? myUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastStroke, [], {
              #notebookId: notebookId,
              #strokeData: strokeData,
              #myUserId: myUserId,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> broadcastTextBlock({
    required int? notebookId,
    required Map<String, dynamic>? textData,
    String? myUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastTextBlock, [], {
              #notebookId: notebookId,
              #textData: textData,
              #myUserId: myUserId,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> broadcastImageBlock({
    required int? notebookId,
    required Map<String, dynamic>? imageData,
    String? myUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastImageBlock, [], {
              #notebookId: notebookId,
              #imageData: imageData,
              #myUserId: myUserId,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> broadcastImageUploading({
    required int? notebookId,
    required String? myUserId,
    required bool? isUploading,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastImageUploading, [], {
              #notebookId: notebookId,
              #myUserId: myUserId,
              #isUploading: isUploading,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> broadcastViewport({
    required int? notebookId,
    required Map<String, dynamic>? viewportData,
    required String? myUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastViewport, [], {
              #notebookId: notebookId,
              #viewportData: viewportData,
              #myUserId: myUserId,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> broadcastFollowUpdate({
    required int? notebookId,
    required String? myUserId,
    String? followingUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastFollowUpdate, [], {
              #notebookId: notebookId,
              #myUserId: myUserId,
              #followingUserId: followingUserId,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> broadcastPageEvent({
    required int? notebookId,
    required Map<String, dynamic>? pageData,
    required String? myUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastPageEvent, [], {
              #notebookId: notebookId,
              #pageData: pageData,
              #myUserId: myUserId,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> broadcastHandEvent({
    required int? notebookId,
    required String? myUserId,
    required bool? isRaised,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastHandEvent, [], {
              #notebookId: notebookId,
              #myUserId: myUserId,
              #isRaised: isRaised,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> broadcastVoiceCallStarted({
    required int? notebookId,
    required String? myUserId,
    required String? senderName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastVoiceCallStarted, [], {
              #notebookId: notebookId,
              #myUserId: myUserId,
              #senderName: senderName,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> broadcastLiveInvite({
    required int? notebookId,
    required String? myUserId,
    required String? senderName,
    required List<String>? targetUserIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastLiveInvite, [], {
              #notebookId: notebookId,
              #myUserId: myUserId,
              #senderName: senderName,
              #targetUserIds: targetUserIds,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> broadcastVoiceStateUpdate({
    required int? notebookId,
    required String? myUserId,
    required bool? isInCall,
    bool? isTalking = false,
    double? audioLevel = 0.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastVoiceStateUpdate, [], {
              #notebookId: notebookId,
              #myUserId: myUserId,
              #isInCall: isInCall,
              #isTalking: isTalking,
              #audioLevel: audioLevel,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> broadcastUserActivity({
    required int? notebookId,
    required String? myUserId,
    required String? activity,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastUserActivity, [], {
              #notebookId: notebookId,
              #myUserId: myUserId,
              #activity: activity,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> broadcastPointerMove({
    required int? notebookId,
    required String? myUserId,
    required _i11.Offset? pos,
    int? pageNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastPointerMove, [], {
              #notebookId: notebookId,
              #myUserId: myUserId,
              #pos: pos,
              #pageNumber: pageNumber,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> broadcastChatMessage({
    required int? notebookId,
    required String? myUserId,
    required String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastChatMessage, [], {
              #notebookId: notebookId,
              #myUserId: myUserId,
              #message: message,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> broadcastAudioMessage({
    required int? notebookId,
    required String? myUserId,
    required String? audioUrl,
    required int? duration,
    bool? isLive = false,
    String? streamMsgId,
    int? segmentIndex,
    bool? isFinal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastAudioMessage, [], {
              #notebookId: notebookId,
              #myUserId: myUserId,
              #audioUrl: audioUrl,
              #duration: duration,
              #isLive: isLive,
              #streamMsgId: streamMsgId,
              #segmentIndex: segmentIndex,
              #isFinal: isFinal,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> requestChatSync({required String? myUserId}) =>
      (super.noSuchMethod(
            Invocation.method(#requestChatSync, [], {#myUserId: myUserId}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendChatSyncResponse({
    required String? targetUserId,
    required List<Map<String, dynamic>>? history,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendChatSyncResponse, [], {
              #targetUserId: targetUserId,
              #history: history,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> requestCollectiveSync({required String? myUserId}) =>
      (super.noSuchMethod(
            Invocation.method(#requestCollectiveSync, [], {
              #myUserId: myUserId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> requestFullState({
    required int? notebookId,
    required String? targetUserId,
    required int? pageNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestFullState, [], {
              #notebookId: notebookId,
              #targetUserId: targetUserId,
              #pageNumber: pageNumber,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deliverFullState({
    required int? notebookId,
    required String? targetUserId,
    required Map<String, dynamic>? pageData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deliverFullState, [], {
              #notebookId: notebookId,
              #targetUserId: targetUserId,
              #pageData: pageData,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> broadcastPageFingerprint({
    required int? notebookId,
    required String? myUserId,
    required int? pageNumber,
    required String? fingerprint,
    int? updatedAt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastPageFingerprint, [], {
              #notebookId: notebookId,
              #myUserId: myUserId,
              #pageNumber: pageNumber,
              #fingerprint: fingerprint,
              #updatedAt: updatedAt,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> broadcastCloudSyncSignal({
    required int? notebookId,
    required String? myUserId,
    required int? pageNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastCloudSyncSignal, [], {
              #notebookId: notebookId,
              #myUserId: myUserId,
              #pageNumber: pageNumber,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> broadcastGlobalAction({
    required int? notebookId,
    required Map<String, dynamic>? actionData,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastGlobalAction, [], {
              #notebookId: notebookId,
              #actionData: actionData,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> broadcastReaction({
    required int? notebookId,
    required String? myUserId,
    required String? reaction,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#broadcastReaction, [], {
              #notebookId: notebookId,
              #myUserId: myUserId,
              #reaction: reaction,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  List<Map<String, dynamic>> getConnectedUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getConnectedUsers, []),
            returnValue: <Map<String, dynamic>>[],
          )
          as List<Map<String, dynamic>>);

  @override
  void leaveNotebookChannel(int? notebookId) => super.noSuchMethod(
    Invocation.method(#leaveNotebookChannel, [notebookId]),
    returnValueForMissingStub: null,
  );

  @override
  void disconnect() => super.noSuchMethod(
    Invocation.method(#disconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> listenToUserAccount(
    int? userId,
    Function? onGlobalSyncNeeded,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listenToUserAccount, [
              userId,
              onGlobalSyncNeeded,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void updateUserTalkingState(String? userId, bool? isTalking) =>
      super.noSuchMethod(
        Invocation.method(#updateUserTalkingState, [userId, isTalking]),
        returnValueForMissingStub: null,
      );

  @override
  void updateUserActivityState(String? userId, String? activity) =>
      super.noSuchMethod(
        Invocation.method(#updateUserActivityState, [userId, activity]),
        returnValueForMissingStub: null,
      );

  @override
  void updateUserHandState(String? userId, bool? isRaised) =>
      super.noSuchMethod(
        Invocation.method(#updateUserHandState, [userId, isRaised]),
        returnValueForMissingStub: null,
      );
}
